# docker-compose-example.prod.yml
# ⚠ 이 파일은 예시입니다.
# 'docker-compose.prod.yml'로 이름을 바꾸고
# 프로젝트에 맞게 값을 입력하여 사용하세요.

services: # 생성되는 순서 중요

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m" # 힙 크기 지정. 기본 1GB
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Redis 서비스
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Spring Boot 애플리케이션
  app: # 🔧 프로젝트에 맞게 값을 설정 해주세요.
    image: myouth/socketmessenger:latest # 🔧 프로젝트에 맞게 값을 설정 해주세요.
    container_name: socketmessenger # 🔧 프로젝트에 맞게 값을 설정 해주세요.
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - .env.common
      - .env.prod
    depends_on:
      - redis
    environment:  # 🔧 프로젝트에 맞게 .env.prod 파일의 값으로 변경해주세요.
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_POSTGRESQL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME_POSTGRESQL}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_POSTGRESQL}
#      SPRING_REDIS_HOST: redis # ${SPRING_REDIS_HOST}
#      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
